version: "3"

services:  
  database:
    container_name: database
    image: mysql:5.7  
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frello
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    # ports:
    #   - "4306:3306"
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  php:
    container_name: php
    working_dir: "/var/www/html"
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - database

volumes:
  mysql: